### ISSUE TITLE
Error on build 

### ISSUE THREAD

**Issue by JonathanRiche** [unlocomqx/sveltekit-shopify-starter#2]
When trying to run the build script I'm getting this error when the build tries to transform the hooks script(everything works fine in local/dev)

```bash
.svelte-kit/output/server/manifest.json                     
.svelte-kit/output/server/entries/endpoints/index.ts.js      
.svelte-kit/output/server/entries/endpoints/info.ts.js       
.svelte-kit/output/server/entries/pages/__layout.svelte.js    
.svelte-kit/output/server/entries/fallbacks/error.svelte.js  
.svelte-kit/output/server/entries/pages/index.svelte.js       
.svelte-kit/output/server/index.js                           
.svelte-kit/output/server/chunks/index-581aedbd.js            
.svelte-kit/output/server/chunks/client-7d40c0d0.js           
.svelte-kit/output/server/chunks/index-d69ca73c.js           
.svelte-kit/output/server/chunks/ssr-59b5ebf3.js            
.svelte-kit/output/server/chunks/Shop-69fbb9e8.js             
.svelte-kit/output/server/chunks/hooks-2e2d2aef.js
301 / -> /auth?shop=null
> ENOENT: no such file or directory, open 'C:\Users\jrich\Development\THELNK\shopifysvelte\shopifyv2\.svelte-kit/output/prerendered/pages/auth?shop=null'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2153:35)
    at save (file:///C:/Users/jrich/Development/THELNK/shopifysvelte/shopifyv2/node_modules/@sveltejs/kit/dist/chunks/index2.js:1185:4)
    at visit (file:///C:/Users/jrich/Development/THELNK/shopifysvelte/shopifyv2/node_modules/@sveltejs/kit/dist/chunks/index2.js:1090:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```
I noticed when inspecting the event.url its when sveltekit is trying to build the pre rendered pages

```bash
URL {
  href: 'http://sveltekit-prerender/',
  origin: 'http://sveltekit-prerender',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'sveltekit-prerender',
  hostname: 'sveltekit-prerender',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
  301 / -> /auth?shop=null
URL {
  href: 'http://sveltekit-prerender/auth?shop=null',
  origin: 'http://sveltekit-prerender',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'sveltekit-prerender',
  hostname: 'sveltekit-prerender',
  port: '',
  pathname: '/auth',
  search: '?shop=null',
  searchParams: URLSearchParams { 'shop' => 'null' },
  hash: ''
}

```

**Comment by unlocomqx** [comment]
I pushed some commits to disable pre-rendering for now. 

Feel free to check the latest revision

**Comment by JonathanRiche** [comment]
perfect this plus your app-bridge fix got it working for me in prod!

**Comment by unlocomqx** [comment]
that's great, 

enjoy 🎊
